# Generated by Django 4.1.5 on 2023-01-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sales Contact", "Sales Contact"),
                    ("Support Contact", "Support Contact"),
                ],
                max_length=50,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
